[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme iceberg
'''
